// app/layout.tsx

import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "./globals.css"
import { Inter } from 'next/font/google'

// Initialize Inter font
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="el" className={inter.className}>
      <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
          defer
        />
      </head>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}